name: payflow-stack

networks:
  payflow-net:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:

services:
  backend:
    image: alsduq1117/payflow:latest
    env_file: ../.env
    ports:
      - "8080:8080"           # 외부 직접 접근 안 쓰면 주석 처리 가능
    networks: [payflow-net]
    restart: unless-stopped

  frontend:
    image: alsduq1117/payflow-frontend:latest
    depends_on: [ backend ]
    ports:
      - "80:80"           # 외부 직접 접근 안 쓰면 주석 처리 가능
    networks: [ payflow-net ]
    restart: unless-stopped
    volumes:
      - /home/ubuntu/app/deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  prometheus:
    image: prom/prometheus:v2.53.0
    depends_on: [backend]
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks: [payflow-net]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    depends_on: [prometheus]
    environment:
      - GF_SERVER_ROOT_URL=https://payflow.my/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SAMESITE=None
      - GF_SECURITY_COOKIE_SECURE=true
    volumes:
      - grafana-data:/var/lib/grafana
    networks: [payflow-net]
    restart: unless-stopped